# Generated by Django 5.1.3 on 2024-11-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookes',
            new_name='Book',
        ),
    ]
