# Generated by Django 5.1.3 on 2024-11-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_bookes_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_year',
            new_name='published_year',
        ),
    ]
